#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-remotes
Version  : 2.0.2
Release  : 4
URL      : https://cran.r-project.org/src/contrib/remotes_2.0.2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/remotes_2.0.2.tar.gz
Summary  : R Package Installation from Remote Repositories, Including
Group    : Development/Tools
License  : GPL-2.0+ MIT
Requires: R-rlang
BuildRequires : R-rlang
BuildRequires : buildreq-R

%description
'BitBucket', or plain 'subversion' or 'git' repositories. This package
    is a lightweight replacement of the 'install_*' functions in 'devtools'.
    Indeed most of the code was copied over from 'devtools'.

%prep
%setup -q -c -n remotes

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1540917509

%install
export SOURCE_DATE_EPOCH=1540917509
rm -rf %{buildroot}
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library remotes
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library remotes
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library remotes
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library remotes|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/remotes/DESCRIPTION
/usr/lib64/R/library/remotes/INDEX
/usr/lib64/R/library/remotes/Meta/Rd.rds
/usr/lib64/R/library/remotes/Meta/features.rds
/usr/lib64/R/library/remotes/Meta/hsearch.rds
/usr/lib64/R/library/remotes/Meta/links.rds
/usr/lib64/R/library/remotes/Meta/nsInfo.rds
/usr/lib64/R/library/remotes/Meta/package.rds
/usr/lib64/R/library/remotes/Meta/vignette.rds
/usr/lib64/R/library/remotes/NAMESPACE
/usr/lib64/R/library/remotes/NEWS.md
/usr/lib64/R/library/remotes/R/remotes
/usr/lib64/R/library/remotes/R/remotes.rdb
/usr/lib64/R/library/remotes/R/remotes.rdx
/usr/lib64/R/library/remotes/README.markdown
/usr/lib64/R/library/remotes/doc/dependencies.Rmd
/usr/lib64/R/library/remotes/doc/dependencies.html
/usr/lib64/R/library/remotes/doc/index.html
/usr/lib64/R/library/remotes/help/AnIndex
/usr/lib64/R/library/remotes/help/aliases.rds
/usr/lib64/R/library/remotes/help/paths.rds
/usr/lib64/R/library/remotes/help/remotes.rdb
/usr/lib64/R/library/remotes/help/remotes.rdx
/usr/lib64/R/library/remotes/html/00Index.html
/usr/lib64/R/library/remotes/html/R.css
